changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableScripts: false

logFilters:
  - code: YN0004
    level: info
  - code: YN0005
    level: discard
  - code: YN0006
    level: discard

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: '@yarnpkg/plugin-snuggery'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.2.4.cjs
