changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

enableScripts: false

logFilters:
  - code: YN0005
    level: discard
  - code: YN0006
    level: discard

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-snuggery.cjs
    spec: "@yarnpkg/plugin-snuggery"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
